<?php
/**
 * Created by PhpStorm.
 * User: liyassoladogun
 * Date: 1/24/19
 * Time: 5:10 PM
 */

namespace SimplifiedMagento\CustomAdmin\Model;


use Magento\Ui\DataProvider\AbstractDataProvider;
use simplifiedMagento\firstModule\Model\ResourceModel\AffiliateMember\CollectionFactory;

class DataProvider extends AbstractDataProvider
{


    public function __construct(
        CollectionFactory $collectionFactory,
        $name, $primaryFieldName, $requestFieldName, array $meta = [], array $data = [])
    {
        $this->collection = $collectionFactory->create();
        parent::__construct($name, $primaryFieldName, $requestFieldName, $meta, $data);
    }

    public function getData()
    {
        if(isset($this->loadedData)) {
            return $this->loadedData;
        }

        $items= $this->collection->getItems();

        $this->loadedData = array();

        /** @var \SimplifiedMagento\firstModule\Model\AffiliateMember $member */
        foreach ($items as $member) {
            $this->loadedData[$member->getId()]['member'] = $member->getData();
        }

        return  $this->loadedData; // TODO: Change the autogenerated stub
    }
}