<form class="" action="<?php echo $block->getBaseUrl().'supertntalpha3/index/save'; ?>" id="impac-supertntalpha3-form" method="post" enctype='multipart/form-data'  data-mage-init='{"validation": {}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span>Test Form For Impac_SUPERtntALPHA3 Module <a href="<?php echo $block->getBaseUrl().'supertntalpha3/index/list'; ?>">(Visit List Page)</a></span></legend><br>
        <div class="field note no-label">Write here anything you want.</div>
        <div class="field nombreOficina">
            <label class="label" for="nombreOficina"><span>Nombre</span></label>
            <div class="control">
                <input name="nombreOficina" id="nombreOficina" title="Nombre" value="" class="input-text" type="text" data-validate="{required:true}">
            </div>
        </div>
        <div class="field author">
            <label class="label" for="author"><span>Direccion</span></label>
            <div class="control">
                <input name="author" id="Direccion" title="Direccion" value="" class="input-text" type="text" data-validate="{required:true}">
            </div>
        </div>
        <div class="field content">
            <label class="label" for="content"><span>Telefono</span></label>
            <div class="control">
                <textarea name="content" id="Telefono" title="Telefono" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="Submit" class="action submit primary">
                <span>Submit</span>
            </button>
        </div>
    </div>
</form>