
<?php
    $collection = $block->getValoresCollection();
    if($collection->count() > 0):
     if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
    <table class="data table" id="valores-data-table">
        <caption class="table-caption">Impac Valores Data</caption>
        <thead>
            <tr>
                <th scope="col" class="col idOficina">idOficina</th>
                <th scope="col" class="col nombreOficina">Peso Máximo</th>
                <th scope="col" class="col image">Costo A</th>
                <th scope="col" class="col created_at">Costo B</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($collection as $key => $data): ?>
                <tr>
                    <td data-th="idOficina" class="col idOficina"><?php echo $data->getId(); ?></td>
                    <td data-th="pesoMaximo" class="col pesoMaximo"><?php echo $data->getPesoMaximo(); ?></td>
                    <td data-th="costoA" class="col costoA"><?php echo $data->getCostoA(); ?></td>
                    <td data-th="costoB" class="col costoB"><?php echo $data->getCostoB(); ?></td>
                    <td data-th="Actions" class="col actions">
                        <?php $id = ($data->getId()) ? $data->getId() : $data['idOficina']; ?>
                        <!-- "$data->getTesting13Id()" was not working when I generated Vky_Testing13 module. That's why I had to place above line. -->
                        <a href="<?php echo $block->getBaseUrl().'valores/index/Valoresview/id/'.$id; ?>" class="action view">
                            <span>View</span>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
<?php else: ?>
    <h2>We couldn't find any records</h2>
<?php endif; ?>