<form class="" action="<?php echo $block->getBaseUrl().'valores/index/save'; ?>" id="impac-valores-form" method="post" enctype='multipart/form-data'  data-mage-init='{"validation": {}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span>Test Form For Añadir Valores <a href="<?php echo $block->getBaseUrl().'valores/index/Valoreslist'; ?>">(Visit List Page)</a></span></legend><br>
        <div class="field note no-label">Write here anything you want.</div>
        <div class="field pesoMaximo">
            <label class="label" for="pesoMaximo"><span>Peso Maximo</span></label>
            <div class="control">
                <input name="pesoMaximo" id="pesoMaximo" title="pesoMaximo" value="" class="input-text" type="text" data-validate="{required:true}">
            </div>
        </div>
        <div class="field costoA">
            <label class="label" for="author"><span>Costo A</span></label>
            <div class="control">
                <input name="costoA" id="costoA" title="costoA" value="" class="input-text" type="text" data-validate="{required:true}">
            </div>
        </div>
        <div class="field costoB">
            <label class="label" for="content"><span>Costo B</span></label>
            <div class="control">
                <textarea name="costoB" id="costoB" title="costoB" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="Submit" class="action submit primary">
                <span>Submit</span>
            </button>
        </div>
    </div>
</form>